packaging_format = 2

id = "phpsysinfo"
name = "PhpSysInfo"
description.en = "Customizable PHP script that displays information about your system nicely"
description.fr = "Script PHP paramétrable qui affiche des informations sur votre système"

version = "3.4.4~ynh1"

maintainers = ["inrepublica"]

[upstream]
license = "GPL-3.0-only"
website = "https://phpsysinfo.github.io/phpsysinfo/"
demo = "http://phpsysinfo.sourceforge.net/multi/index.php?disp=bootstrap&xml=raspbian"
admindoc = "https://phpsysinfo.github.io/phpsysinfo/"
code = "https://github.com/phpsysinfo/phpsysinfo/"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/phpsysinfo"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    help.en = "Be careful, putting this application in public will expose some sensitive information."
    help.fr = "Attention mettre cette application en publique exposera certaines informations sensibles."
    type = "group"
    default = "admins"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["ast", "bg", "ca", "cz", "da", "de", "en", "es", "et", "fi", "fr", "gl", "gr", "he", "hu", "is", "it", "ja", "ko", "nl", "no", "pl", "pt-br", "pt-pt", "ro", "ru", "sk", "sl", "sv", "th", "tr", "tw", "uk", "zh"]
    default = "en"

    [install.display_mode]
    ask.en = "Display Mode?"
    ask.fr = "Mode d'affichage ?"
    type = "select"
    choices = ["auto", "dynamic", "static", "bootstrap"]
    default = "auto"

[resources]
        [resources.sources.main]
        url = "https://github.com/phpsysinfo/phpsysinfo/archive/refs/tags/v3.4.4.tar.gz"
        sha256 = "fab71f09a09881c7fab78f452b4da907e306a5f34069cdeb94f7d1adcbcfac0e"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = ["php8.3-fpm", "php8.3-xml"]
