#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# See comments in install script
app=phpsysinfo

# Source YunoHost helpers
. /usr/share/yunohost/helpers

# Backup sources & data
ynh_backup "/var/www/${app}" "sources"

# Copy NGINX configuration
domain=$(ynh_app_setting_get "$app" domain)
ynh_backup "/etc/nginx/conf.d/${domain}.d/${app}.conf" "nginx.conf"