#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

ynh_config_add_phpfpm

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_replace --match="DEFAULT_LANG=\"en\"" --replace="DEFAULT_LANG=\"$language\"" --file="$install_dir/phpsysinfo.ini.new"
ynh_replace --match="DEFAULT_DISPLAY_MODE=\"auto\"" --replace="DEFAULT_DISPLAY_MODE=\"$display_mode\"" --file="$install_dir/phpsysinfo.ini.new"

### Rename phpsysinfo.ini.new in phpsysinfo.ini
mv "$install_dir"/phpsysinfo.ini.new "$install_dir"/phpsysinfo.ini

ynh_store_file_checksum "$install_dir/phpsysinfo.ini"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
