#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

ynh_config_add_nginx

ynh_config_add_phpfpm

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_backup_if_checksum_is_different "$install_dir/phpsysinfo.ini"

ynh_replace --match="DEFAULT_LANG=\"en\"" --replace="DEFAULT_LANG=\"$language\"" --file="$install_dir/phpsysinfo.ini.new"
ynh_replace --match="DEFAULT_DISPLAY_MODE=\"auto\"" --replace="DEFAULT_DISPLAY_MODE=\"$display_mode\"" --file="$install_dir/phpsysinfo.ini.new"

### Rename phpsysinfo.ini.new in phpsysinfo.ini
mv "$install_dir"/phpsysinfo.ini.new "$install_dir"/phpsysinfo.ini

# Recalculate and store the checksum of the file for the next upgrade.
ynh_store_file_checksum "$install_dir/phpsysinfo.ini"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
