#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# Define app
app=phpsysinfo
version=3.2.5
md5_source=08875b31a9a7a662473d8cbe866059e7

# Source YunoHost helpers
. /usr/share/yunohost/helpers

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)
path=$(ynh_app_setting_get "$app" path)
is_public=$(ynh_app_setting_get "$app" is_public)
language=$(ynh_app_setting_get "$app" language)
display_mode=$(ynh_app_setting_get "$app" display_mode)

# Download source, check md5, untar, copy it
sudo wget https://github.com/phpsysinfo/phpsysinfo/archive/v$version.tar.gz -O /tmp/phpsysinfo.tar.gz

# Check md5
md5_check=($(md5sum /tmp/phpsysinfo.tar.gz))
if [ $md5_source != $md5_check ]
then
        ynh_die "the download is corrupted (md5 different)"
fi

# untar and copy it
sudo tar -xvf /tmp/phpsysinfo.tar.gz -C /tmp/
final_path=/var/www/$app
sudo mkdir -p $final_path
sudo cp -a /tmp/phpsysinfo-$version/. $final_path

# Set permissions to app files
sudo chown -R root:root $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# If app is public, add url to SSOWat conf as skipped_uris
if [ "$is_public" = "Yes" ];
then
  # See install script
  ynh_app_setting_set "$app" unprotected_uris "/"
  # Remove old settings
  # ynh_app_setting_delete "$app" skipped_uris
fi

# Restart services
sudo service nginx reload